### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by taylanmusluman** [EarlRamirez/snipeit_iso#18]
Hi there, thanks for making this first of all!

Everything went smoothly with the install, it was working perfectly. However after 1-2h every time, the Snipe-IT page under the IP address starts giving a "Page not found, HTTP ERROR 500". I created another VM with another IP as well and tried a fresh install, same result. Worked just fine for 2h then the same error. These VMs are accessible via SSH and everything seems to be fine. Any ideas what might be causing it?

**Comment by taylanmusluman** [comment]
Some more context from /var/www/html/snipeit/storage/logs

production.ERROR: ErrorException: Trying to get property 'privacy_policy_link' of non-object in /var/www/html/snipeit/storage/framework/views/2003de040112dbb9f4ecec8a498fd2f53ae90abae90aba.php:59

Next ErrorException: Trying to get property 'privacy_policy_link' of non-object (View: /var/www/html/snipeit/resources/views/layouts/basic.blade.php) in /var/www/html/snipeit/storage/framework/views/2003de040112dbb9f4ecec8a498fd2f53ae90aba.php:59

Next ErrorException: Trying to get property 'privacy_policy_link' of non-object (View: /var/www/html/snipeit/resources/views/layouts/basic.blade.php) (View: /var/www/html/snipeit/resources/views/layouts/basic.blade.php) in /var/www/html/snipeit/storage/framework/views/2003de040112dbb9f4ecec8a498fd2f53ae90aba.php:59

**Comment by EarlRamirez** [comment]
@taylanmusluman, thanks for informing me about this issue, I'll check it now and will get back to you shortly.

In the meantime, you can upgrade to the latest version of Snipe-IT and let me know if you are still experiencing the same issue.

To upgrade do the following.
* cd /var/www/html/snipeit
* sudo -u apache php upgrade.php

**Comment by EarlRamirez** [comment]
500 errors from the web server, I spin up a VM and do not see these errors or behaviour can you share the httpd error logs.

**Comment by EarlRamirez** [comment]
Okay, I experienced the same issue but with different errors, after upgrading Snipe-IT it was accessible again, I'll let it run for a few hours and see if the upgrade is the permanent fix and update the ISO, test it and upload it.

**Comment by EarlRamirez** [comment]
@taylanmusluman the ISO was created and uploaded, the root cause of the error was caused by missing files in vendor/psy, it was there when the OS was initially installed; however, was deleted after, don't know what caused it though. The new ISO ships with the latest version and was tested for over 24 hours.

Thanks for reporting the issue, the issue will remain open until I receive a confirmation from you.

**Comment by EarlRamirez** [comment]
@taylanmusluman try with the new ISO and let me know how it goes.

**Comment by taylanmusluman** [comment]
@EarlRamirez tested now and it works, thanks!

**Comment by EarlRamirez** [comment]
Glad that it worked did you grab the latest version, it includes SSL support.

**Comment by taylanmusluman** [comment]
@EarlRamirez yeah I used the latest :)

**Comment by EarlRamirez** [comment]
Thanks very much :)
