### ISSUE TITLE
Need to disable https,

### ISSUE THREAD

**Issue by GoldBond007** [EarlRamirez/snipeit_iso#34]
I need to know how to completely disable https on my Snipe IT instance. I don't need https enable as it will be running on a closed internal network. I want to be able to access SNIPE IT with http instead.

**Comment by EarlRamirez** [comment]
You will need to uncomment a few lines from snipeit.conf and permit port 80
through the firewall, will be in front of my computer soon so will provide
you with the details

**Comment by GoldBond007** [comment]
Okay, Since I don't really need HTTPS for this environment, the server I am running SNIPE IT doesn't go out to the internet, it's isolated on a separate office network at the moment. Please let me know if you need anything else.

**Comment by EarlRamirez** [comment]
Here are the steps to remove HTTPS
- Edit /etc/httpd/conf.d/snipeit.conf and do the following 
- Replace <VirtualHost *:443> to <VirtualHost *:**80**>
- Comment out all lines that starts with **SSL**
- Save and close the file
- Edit /var/www/html/snipeit/.env and replace https with **http** in the APP_URL
- Restart httpd daemon `systemctl retsart httpd`
- Update firewall rules `firewall-cmd --permanent --add-service=http && firewall-cmd --permanent --remove-service=https && firewall-cmd --reload`
- You can now access your server via HTTP

Let me know if this helps

**Comment by GoldBond007** [comment]
This worked! thank you Earl

**Comment by EarlRamirez** [comment]
Awesome, glad it worked for you.
