### ISSUE TITLE
Cant Install phpmyadmin

### ISSUE THREAD

**Issue by ardiansahlai** [EarlRamirez/snipeit_iso#35]
Hi, I cant Install phpmyadmin on fresh install snipeit using iso the error is 

**Error: php73-common conflicts with php72u-common-7.2.26-1.el7.ius.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest**

After that error i tried to install it by **" yum install phpmyadmin --skip-broken "**

after that there is new error 

**Downloading packages:
warning: /var/cache/yum/x86_64/7/ius/packages/php72u-cli-7.2.26-1.el7.ius.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 4b274df2: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/IUS-COMMUNITY-GPG-KEY

The GPG keys listed for the "IUS Community Packages for Enterprise Linux 7 - x86_64" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.

 Failing package is: php72u-cli-7.2.26-1.el7.ius.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/IUS-COMMUNITY-GPG-KEY**

can you please help me?

**Comment by EarlRamirez** [comment]
Try **yum clean all && yum -y update** and try again, let me know how it goes

**Comment by ardiansahlai** [comment]
> Try **yum clean all && yum -y update** and try again, let me know how it goes

after do that there is another error
Error: Package: php-tidy-5.4.16-9.el7.x86_64 (epel)
           Requires: php(zend-abi) = 20100525-64
           Installed: php-common-7.3.13-1.el7.remi.x86_64 (@remi-php73)
               php(zend-abi) = 20180731-64
           Available: php-common-5.4.16-46.el7.x86_64 (base)
               php(zend-abi) = 20100525-64
           Available: php-common-5.4.16-46.1.el7_7.x86_64 (updates)
               php(zend-abi) = 20100525-64
Error: Package: phpMyAdmin-4.4.15.10-4.el7.noarch (epel)
           Requires: php-zip
           Available: php-common-5.4.16-46.el7.x86_64 (base)
               php-zip
           Available: php-common-5.4.16-46.1.el7_7.x86_64 (updates)
               php-zip
           Installed: php-common-7.3.13-1.el7.remi.x86_64 (@remi-php73)
               Not found
Error: Package: php-tidy-5.4.16-9.el7.x86_64 (epel)
           Requires: php(api) = 20100412-64
           Installed: php-common-7.3.13-1.el7.remi.x86_64 (@remi-php73)
               php(api) = 20180731-64
           Available: php-common-5.4.16-46.el7.x86_64 (base)
               php(api) = 20100412-64
           Available: php-common-5.4.16-46.1.el7_7.x86_64 (updates)
               php(api) = 20100412-64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by ardiansahlai** [comment]
after i  success installed phpmyadmin , the snipe-it turn to http error 500

**Comment by ardiansahlai** [comment]
i solved my problem, the problem is on the IUS repository, after i Reinstall it i can install the phpmyadmin, thanks all
