### ISSUE TITLE
Preflight Check

### ISSUE THREAD

**Issue by EarlRamirez** [EarlRamirez/snipeit_iso#4]
The preflight check fails for /var/www/html/snipeit/.env

Need to correct the permission and change the SELinux label for the directory.

![image](https://user-images.githubusercontent.com/12306859/41484360-8807cffa-70aa-11e8-97a5-f3831df171dd.png)

**Comment by EarlRamirez** [comment]
The file cannot be accessed even if the error persists, closing the issue

**Comment by 1823alex** [comment]
I have the same error, how do you fix it?

**Comment by EarlRamirez** [comment]
I didn't bother to fix it because the file cannot be accessed, if you point your browser to https://Your_snipe-IT_IP_address/.env, you will get an error that the file cannot be found or doesn't exist. Hence, the reason why I didn't bother to fix it because it doesn't pose any security risk to the system. This error is caused by the way how Snipe-IT checks the .env file.

Let me know if this response will suffice.
